version: "3"

services:

  web:
    container_name: bugebo-dev-web
    build: ./docker
    depends_on:
      - database
    ports:
      - "18080:8080"
    volumes:
      - ./:/var/www/html
      - ./docker/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./docker/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini

  database:
    image: mariadb:10.9
    container_name: bugebo-dev-db
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: db
      MYSQL_PASSWORD: db
    volumes:
      - dev-db-data:/var/lib/mysql

volumes:
  dev-db-data:
