version: "3"

volumes:
  dev-bugebo-db-data:

services:

  web:
    container_name: dev-bugebo-api
    build: ./docker
    ports:
      - "18080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini

  database:
    image: mariadb:10.9
    container_name: dev-bugebo-db
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: db
      MYSQL_PASSWORD: db
    volumes:
      - dev-bugebo-db-data:/var/lib/mysql
