name: 🐛 Fehlerbericht / Bug Report
description: Erstellung eines Fehlerberichtes / Create Issues for a Bug
labels: Bug

body:
  - type: input
    id: affected-versions
    attributes:
      label: Welche Versionen sind betroffen / Version(s) affected
      placeholder: x.y.z
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Beschreibung / Description
      description: Eine klare und prägnante Beschreibung des Problems / A clear and concise description of the problem
    validations:
      required: true
  - type: textarea
    id: how-to-reproduce
    attributes:
      label: Wie kann man diesen reproduzieren / How to reproduce
      description: |
        ⚠️ Dies ist der wichtigste Teil des Berichts ⚠️.
        Ohne eine Möglichkeit, Ihr Problem einfach zu reproduzieren, haben wir kaum eine Chance, Ihnen zu helfen und 
        an einer Lösung zu arbeiten. Bitte nehmen Sie sich die Zeit, uns einige Codes und/oder Konfigurationen zu zeigen,
        die andere benötigen, um das Problem leicht zu reproduzieren.
        
        ⚠️  This is the most important part of the report ⚠️
        Without a way to easily reproduce your issue, there is little chance we will be able to help you and work on a fix.
        Please, take the time to show us some code and/or config that is needed for others to reproduce the problem easily.
    validations:
      required: true
  - type: textarea
    id: possible-solution
    attributes:
      label: Mögliche Lösung / Possible Solution
      description: |
        Optional: nur wenn Sie Vorschläge für eine Lösung/einen Grund für den Fehler haben.
        Zögern Sie nicht, einen Pull-Request mit Ihrer Lösung zu erstellen, das hilft, schneller Feedback zu bekommen.
        
        Optional: only if you have suggestions on a fix/reason for the bug
        Don't hesitate to create a pull request with your solution, it helps get faster feedback.
  - type: textarea
    id: additional-context
    attributes:
      label: Zusätzlicher Kontext / Additional Context
      description: "Optional: weitere Informationen über das Problem: Protokollmeldungen, Screenshots usw.
                    Optional: any other context about the problem: log messages, screenshots, etc."

