name: 🚀 Funktionsanfrage / Feature Request
description: Ideen für neue Funktionen und Verbesserungen / Ideas for new features and improvements
body:
    - type: textarea
      id: description
      attributes:
          label: Beschreibung / Description
          description: |
              Eine klare und prägnante Beschreibung der neuen Funktion.
              A clear and concise description of the new feature
      validations:
          required: true
    - type: textarea
      id: example
      attributes:
          label: Beispiel / Example
          description: |
              Ein einfaches Beispiel für die neue Funktion in Aktion (einschließlich PHP-Code, YAML-Konfiguration usw.)
              Wenn die neue Funktion eine bestehende Funktion ändert, fügen Sie einen einfachen Vorher/Nachher-Vergleich bei.
              
              A simple example of the new feature in action (include PHP code, YAML config, etc.)
              If the new feature changes an existing feature, include a simple before/after comparison.
