name: PHP Lint Check

on:
  push:
    paths:
      - "**.php"

  pull_request:
    paths:
      - "**.php"
      -
permissions:
  contents: read

jobs:
  phplint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: PHP Lint
        uses: overtrue/phplint@8.1
        with:
          path: .
          options: --exclude=*.log
